# Generated by Django 4.1 on 2022-08-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
