# Generated by Django 4.1 on 2022-08-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_words', '0004_alter_user_google_id_alter_user_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
