# Generated by Django 4.1 on 2022-08-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_words', '0005_alter_user_google_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('original', 'user')},
        ),
    ]
