# Generated by Django 4.1 on 2022-08-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_words', '0006_alter_word_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_words',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='send_to_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='send_to_phone',
            field=models.BooleanField(default=False),
        ),
    ]
