# Generated by Django 4.1 on 2022-08-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_words', '0008_word_saved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='saved_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
